### ISSUE TITLE
Horizontal width on mobile view

### ISSUE THREAD

**Issue by Sam-Blundell** [TylerGilman/TylerGilman.com#1]
Observed on OnePlus 7 Pro
Screen res 412x892

Horizontal width seems to exceed view dimensions. Possibly being pushed out due to the navbar fishtank being wider than the page?

Fishtank on projects page also seems to be pushing the width out.

When accessing projects page via the "view my projects" button on the home page the page is much wider compared with accessing via the projects option in the top nav.

![Screenshot_2024-12-20-16-37-20-23_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/cc2f8418-2998-4c63-9226-fdc4287fd11d)

![Screenshot_2024-12-20-16-37-31-38_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/b28c3c91-2387-465f-a6bd-f2822ac067cf)

![Screenshot_2024-12-20-16-37-36-51_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/ee83d595-c12a-4c97-9c9b-8162a81af386)

**Comment by TylerGilman** [comment]
Thank you for the detailed report! It is now fixed and the fishtank will adjust based on your screen width. I sincerely appreciate the help happy holidays!
